import mongoose from 'mongoose';

const scheduleInstanceSchema = new mongoose.Schema(
  {
    scheduleId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Schedule',
      required: true,
    },
    classDate: {
      type: Date,
      required: true,
    },
    classStatus: {
      type: String,
      enum: [
        'scheduled', // Default - based on recurrence
        'held', // Successfully held
        'cancelled', // Explicitly cancelled
        'rescheduled', // Same day, different time/location
        'postponed', // Moved to another day
        'missed', // No update, class didn’t happen
      ],
      default: 'scheduled',
    },
    rescheduledToDate: {
      type: Date,
      default: null,
    },
    updatedTime: {
      start: { type: String }, // "HH:mm"
      end: { type: String },
    },
    updatedLocation: {
      type: String,
      default: null,
    },
    deliveryMode: {
      type: String,
      enum: ['physical', 'virtual', 'hybrid'],
      default: 'physical',
    },
    isAutoGenerated: {
      type: Boolean,
      default: true,
    },
    lecturerMessage: {
      type: String,
      trim: true,
    },
    feedbackFromLecturer: {
      type: String,
      trim: true,
    },
    syllabusTopic: {
      type: String,
      trim: true,
    },
    notes: {
      type: String,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User', // Rep or Admin who updated this instance
    },
    attendanceSummary: {
      totalPresent: { type: Number, default: 0 },
      totalAbsent: { type: Number, default: 0 },
      totalLate: { type: Number, default: 0 },
    },
    studentPresence: [
      {
        studentId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'Student',
        },
        status: {
          type: String,
          enum: ['present', 'absent', 'late'],
          default: 'absent',
        },
      },
    ],
  },
  { timestamps: true }
);

// Indexes
scheduleInstanceSchema.index({ scheduleId: 1, classDate: 1 }, { unique: true });
scheduleInstanceSchema.index({ classDate: 1 });

export default mongoose.model('ScheduleInstance', scheduleInstanceSchema);
